### ISSUE TITLE
Do we really want to create yet another suite of typing tools?

### ISSUE THREAD

**Issue by difosfor** [webcomponents/custom-elements-json#13]
I would really like to have custom element attribute etc. type checking and I'm also really happy about the work you've put into this already, but..

Isn't TypeScript (and/or another typing tool like Flow) in a better position to support all of this? It already supports analyzing, declaring and checking types when it comes to classes, properties and methods etc. Specific support for custom elements including attributes, events, styles etc. and html parsing would have to be added. But in that case it could be used both in full fledged TypeScript projects during compilation and in JavaScript projects that only use the type checking part of their tools.

I don't want to force TypeScript on users. I'm definitely also open to using other existing tooling like Babel or Flow. But it seems that right now`"types": "index.d.ts"` is being published by most NPM packages; wouldn't it be great if that could just include all of this and we wouldn't have to install additional analyzing and linting tooling for our IDE's and CI?

The main issue I do recognize with this is that it will probably be difficult and take a lot of time to get support from the TypeScript team for this and/or contribute to it ourselves there. Still, even if we continue to work on solutions like this I think it might be interesting to simultaneously push and work towards what we think is the best final solution as well.

PS: Sorry if this is not the place to discuss this. But it seems like the related discussion is centering around here, so I've taken the liberty to create this issue.

**Comment by justinfagnani** [comment]
This isn't a repo for hosting typing tools, but to specify a document format to describe custom element metadata that has no other place. TypeScript doesn't know about tag names, attributes, slots, CSS custom variables, etc., and it probably shouldn't. Meanwhile the web components ecosystem has urgent needs to programatically document these things.

**Comment by difosfor** [comment]
Ok, I'll be happy with any improvements we can make in the field of standard custom elements.

Just curious though; why do you think TypeScript should not support this?
They do support JSX. Why not also lit-html (including all of this)?
To some extent they already do: https://github.com/microsoft/typescript-lit-html-plugin
