### ISSUE TITLE
Goals and non-goals

### ISSUE THREAD

**Issue by justinfagnani** [webcomponents/custom-elements-json#2]
It will be useful to discuss and record specific goals and non-goals.

Two examples:

- Many view libraries allow you to create components that they roughly call "web components" that aren't actual W3C custom elements. Some of these can be used in HTML-like syntaxes, like Angular and Vue templates. Should it be a goal or non-goal to describe these components too?
- Custom elements are JavaScript objects, and their descriptions are a superset of JavaScript. Should it be a goal or non-goal of this description format to completely document the JavaScript-side of the component interface?

**Comment by evanplaice** [comment]
A. Non-goal. Exclude framework-specific components since they use their own custom template formats that introduce their own custom semantics.

Ex Angular's event binding syntax 
`<tag (event)="actionRef"><tag>`

Ex React's attribute wrapper propguments

**Comment by kevinmpowell** [comment]
> B. Document as much as possible within reason
> 
> * light|shadow
> * attributes
> * props
> * events
> * slots
> * styles

Any reason not to include `methods` in this list?

**Comment by justinfagnani** [comment]
There seems to be rough consensus around #9 that we should document the JS side of components fairly completely.

Doing cleanup, so I'll close this now.
