### ISSUE TITLE
Starting point

### ISSUE THREAD

**Issue by justinfagnani** [webcomponents/custom-elements-json#3]
Given that some tools already support reading and writing the `custom-elements.json` format, should we take that as a starting point?

On the other hand, @octref has suggested starting from the [VS Code Custom Data Format](https://github.com/microsoft/vscode-custom-data). Whether the format should be based on one IDEs format is a great question to answer.

**Comment by justinfagnani** [comment]
@octref is there a schema for `custom-elements.json`?

**Comment by bahrus** [comment]
[This](https://github.com/microsoft/vscode-html-languageservice/blob/master/docs/customData.schema.json) is probably the schema

**Comment by daKmoR** [comment]
I would start "small" and go for it... and then add more stuff step by step

For all use cases, I worked on (documentation, api playground, catalog) the following was good enough. So I would consider it a good starting point.

one adjustment I might see is to adjust `type` to `typeHint` or so as discussed in https://github.com/webcomponents/custom-elements-json/issues/6#issuecomment-546749135

```json
{
  "version": 2,
  "tags": [
    {
      "name": "demo-wc-card",
      "description": "This is a container looking like a card with a back and front side you can switch",
      "attributes": [
        {
          "name": "header",
          "type": "String",
          "description": "Shown at the top of the card",
          "default": "Your Message",
          "required": true
        }
      ],
      "properties": [
        {
          "name": "header",
          "type": "String",
          "attribute": "header",
          "description": "Shown at the top of the card",
          "default": "Your Message",
          "required": true
        }
      ],
      "events": [
        {
          "name": "side-changed",
          "description": "Fires whenever it switches between front/back"
        }
      ],
      "slots": [
        {
          "name": "",
          "description": "Content inside the card gets displayed on the front page"
        }
      ],
      "cssProperties": [
        {
          "name": "--demo-wc-card-front-color",
          "description": "Font color for the front",
          "type": "Color"
        },
      ]
    }
  ]
}
```

**Comment by octref** [comment]
> Whether the format should be based on one IDEs format is a great question to answer.

1. Custom Data can help VS Code, but with vscode-html-languageservice that loads custom data, it can be used in Emacs (with [lsp-mode](https://github.com/emacs-lsp/lsp-mode)), Vim / Neovim with [COC](https://github.com/neoclide/coc-html), Atom with [ide-html](https://github.com/liuderchi/ide-html), and any editor that support LSP. So from that perspective I'd say Custom Data's feature can be easily made available to others, whereas [web-types](https://github.com/JetBrains/web-types) is specific to JetBrains products.
2. You can take a look at an [example web-type JSON file](https://github.com/JetBrains/web-types/blob/master/examples/vue.web-types.json). It includes every possible field, and it's unclear to me which data point drives what editor features, and anyway those editor features would be limited to JetBrains products. For VS Code's Custom Data, it clearly [documents how the data drives language features](https://github.com/microsoft/vscode-html-languageservice/blob/master/docs/customData.md#language-features), and made available to all other editors through LSP.
3. I think `events`, `slots` are sensible additions to custom-element.json, but not VS Code's Custom Data format. There should be a compilation / transformation step that turns whatever you want to see in auto-completion and hover widgets into a Markdown string for the `description` field.

**Comment by juliexiong** [comment]
> ```
>       "cssProperties": [
>         {
>           "name": "--demo-wc-card-front-color",
>           "description": "Font color for the front",
>           "type": "Color"
>         },
>       ]
>     }
>   ]
> }
> ```

Can an optional default property be defined for `cssProperties`? For my use-case, I have a CSS variable that points to another CSS variable. It would be beneficial for consumers to know they don't have to override this CSS variable if they are creating a dark theme.

```css
--card-background-color: var(--primary-theme-background-color);
```

**Comment by kevinmpowell** [comment]
How about adding support for `methods` ? That's a pretty common thing to surface on a doc site for web component based design systems. They're also already included by web component analyzer's markdown format.

**Comment by justinfagnani** [comment]
We seem to have consensus around #9 (which includes methods @kevinmpowell ). So I'll close this.
