### ISSUE TITLE
Specification format

### ISSUE THREAD

**Issue by justinfagnani** [webcomponents/custom-elements-json#4]
We probably at least want a JSON Schema file describing the spec, at least to validate tool output and to help generate file readers.

JSON Schema isn't the most human readable format though, do we want another format to develop the spec in and present in the main README?

**Comment by bahrus** [comment]
I would propose [TypeScript](https://github.com/YousefED/typescript-json-schema)

**Comment by justinfagnani** [comment]
@bahrus in what way?

**Comment by bahrus** [comment]
Yeah, but on second thought,  being that existing JSON Schema's are being extended / compared, it might be better to stick with the unwieldly JSON Schema format as the source format.

I was playing around with this [editor](https://json-editor.tangramjs.com/), which makes it not too bad.

And there are tools to convert JSON Schema to [markdown](https://github.com/adobe/jsonschema2md/blob/master/examples/docs/deepextending.schema.md)

So I don't really no what the best format to work with would be.

**Comment by evanplaice** [comment]
ITT

Develop it in JSON Schema. Tools can already consume this for validation/completions.

README.md can present the settings using short-hand dot syntax form. Similar to how NPM settings are referenced (ex `pkg.main`). Ex 

## [component].attributes

The custom attributes for the component

Example `string` attribute

```json
"attributes": [
    "label": "text",
    "description": "the component innerText"
]
```

```html
<shadow-wc text="some text"></shadow-wc>`
```

Example `boolean` attribute

...

**Comment by justinfagnani** [comment]
#9 includes both a pretty readable (IMO) TypeScript definition for the format, and a JSON schema file that's included in the repo. This seems like a practical approach.

One downside is having to sync the schema.json file, but if we make the main artifact a published site rather than the repo contents we can not check in the generated schema.json. Will leave that for a separate issue.
